const QUOTES = [
  "The only way to do great work is to love what you do. – Steve Jobs",
  "Success is not the key to happiness. Happiness is the key to success.",
  "Believe you can and you're halfway there. – Theodore Roosevelt",
  "Your limitation—it's only your imagination.",
  "Push yourself, because no one else is going to do it for you.",
  "Great things never come from comfort zones.",
  "Dream it. Wish it. Do it.",
  "Success doesn't just find you. You have to go out and get it.",
  "The harder you work for something, the greater you'll feel when you achieve it.",
  "Don't stop when you're tired. Stop when you're done.",
  "The future belongs to those who believe in the beauty of their dreams. – Eleanor Roosevelt",
  "The secret of getting ahead is getting started. – Mark Twain",
  "It does not matter how slowly you go as long as you do not stop. – Confucius",
  "Everything you've ever wanted is on the other side of fear. – George Addair",
  "Hardships often prepare ordinary people for an extraordinary destiny. – C.S. Lewis",
  "Believe in yourself and all that you are. – Christian D. Larson",
  "If you can dream it, you can do it. – Walt Disney",
  "Start where you are. Use what you have. Do what you can. – Arthur Ashe",
  "Don't watch the clock; do what it does. Keep going. – Sam Levenson",
  "Success is walking from failure to failure with no loss of enthusiasm. – Winston Churchill",
  "Opportunities don't happen, you create them. – Chris Grosser",
  "The best time to plant a tree was 20 years ago. The second best time is now. – Chinese Proverb",
  "Everything you can imagine is real. – Pablo Picasso",
  "The only limit to our realization of tomorrow will be our doubts of today. – Franklin D. Roosevelt",
  "The way to get started is to quit talking and begin doing. – Walt Disney",
  "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. – Roy T. Bennett",
  "Act as if what you do makes a difference. It does. – William James",
  "What you get by achieving your goals is not as important as what you become by achieving your goals. – Zig Ziglar",
  "You miss 100% of the shots you don't take. – Wayne Gretzky",
  "Whether you think you can or you think you can't, you're right. – Henry Ford",
  "Perseverance is not a long race; it is many short races one after the other. – Walter Elliot",
  "It always seems impossible until it's done. – Nelson Mandela",
  "Failure is another stepping stone to greatness. – Oprah Winfrey",
  "I never dreamed about success, I worked for it. – Estée Lauder",
  "The journey of a thousand miles begins with one step. – Lao Tzu",
  "Your passion is waiting for your courage to catch up. – Isabelle Lafleche",
  "Magic is believing in yourself. – Johann Wolfgang von Goethe",
  "If people are doubting how far you can go, go so far that you can't hear them anymore. – Michele Ruiz",
  "We generate fears while we sit. We overcome them by action. – Dr. Henry Link",
  "Do what you can, with what you have, where you are. – Theodore Roosevelt",
  "Be so good they can't ignore you. – Steve Martin",
  "Hustle in silence and let your success make the noise.",
  "Small progress is still progress.",
  "Dream bigger. Do bigger.",
  "Don't limit your challenges. Challenge your limits.",
  "The sun himself is weak when he first rises, and gathers strength and courage as the day gets on. – Charles Dickens",
  "The only person you are destined to become is the person you decide to be. – Ralph Waldo Emerson",
  "Do something today that your future self will thank you for.",
  "Little things make big days. – Isabel Marant",
  "Make each day your masterpiece. – John Wooden",
  "For every reason it's not possible, there are hundreds of people who have faced the same circumstances and succeeded. – Jack Canfield",
  "Doubt kills more dreams than failure ever will. – Suzy Kassem",
  "I've failed over and over and over again in my life and that is why I succeed. – Michael Jordan",
  "A goal is a dream with a deadline. – Napoleon Hill",
  "If you want it, work for it.",
  "Don't quit. Suffer now and live the rest of your life as a champion. – Muhammad Ali",
  "Great things are done by a series of small things brought together. – Vincent Van Gogh",
  "If opportunity doesn't knock, build a door. – Milton Berle",
  "The harder the battle, the sweeter the victory. – Les Brown",
  "Turn your wounds into wisdom. – Oprah Winfrey",
  "We must be willing to let go of the life we planned so as to have the life that is waiting for us. – Joseph Campbell",
  "Life is 10% what happens to us and 90% how we react to it. – Charles R. Swindoll",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us. – Ralph Waldo Emerson",
  "We become what we think about. – Earl Nightingale",
  "Success is not final, failure is not fatal: It is the courage to continue that counts. – Winston Churchill",
  "You are never too old to set another goal or to dream a new dream. – C.S. Lewis",
  "The mind is everything. What you think you become. – Buddha",
  "The only place where success comes before work is in the dictionary. – Vidal Sassoon",
  "The difference between ordinary and extraordinary is that little extra. – Jimmy Johnson",
  "Strive not to be a success, but rather to be of value. – Albert Einstein",
  "Energy and persistence conquer all things. – Benjamin Franklin",
  "If you're going through hell, keep going. – Winston Churchill",
  "Stay foolish to stay sane. – Maxime Lagacé",
  "We can do anything we want to if we stick to it long enough. – Helen Keller",
  "Someday is not a day of the week.",
  "I am not a product of my circumstances. I am a product of my decisions. – Stephen Covey",
  "The harder the conflict, the more glorious the triumph. – Thomas Paine",
  "Don't wait for opportunity. Create it.",
  "You don't need to see the whole staircase, just take the first step. – Martin Luther King Jr.",
  "Work hard in silence, let your success be the noise.",
  "Everything negative – pressure, challenges – is all an opportunity for me to rise. – Kobe Bryant",
  "Go the extra mile. It's never crowded there.",
  "Motivation is what gets you started. Habit is what keeps you going. – Jim Rohn",
  "If you believe it will work out, you'll see opportunities. If you believe it won't, you will see obstacles. – Wayne Dyer",
  "The distance between insanity and genius is measured only by success. – Bruce Feirstein",
  "The best revenge is massive success. – Frank Sinatra",
  "Do not wait to strike till the iron is hot; but make it hot by striking. – William Butler Yeats",
  "Success usually comes to those who are too busy to be looking for it. – Henry David Thoreau",
  "Success is the sum of small efforts, repeated day in and day out. – Robert Collier",
  "Don't stop until you're proud.",
  "The only difference between ordinary and extraordinary is that little extra.",
  "Keep your eyes on the stars and your feet on the ground. – Theodore Roosevelt",
  "You've got to get up every morning with determination if you're going to go to bed with satisfaction. – George Lorimer",
  "It's not whether you get knocked down, it's whether you get up. – Vince Lombardi",
  "The man who moves a mountain begins by carrying away small stones. – Confucius",
  "Set your goals high, and don't stop till you get there. – Bo Jackson",
  "When you feel like quitting think about why you started.",
  "Failure will never overtake me if my determination to succeed is strong enough. – Og Mandino",
  "Aim for the moon. If you miss, you may hit a star. – W. Clement Stone",
  "Do not be embarrassed by your failures, learn from them and start again. – Richard Branson",
  "Action is the foundational key to all success. – Pablo Picasso",
  "The secret of success is to do the common thing uncommonly well. – John D. Rockefeller Jr.",
  "Big journeys begin with small steps.",
  "Don't regret the past, just learn from it. – Ben Ipock",
  "You don't have to be great to start, but you have to start to be great. – Zig Ziglar",
  "Believe in yourself, take on your challenges, dig deep within yourself to conquer fears. – Chantal Sutherland",
  "Change your life today. Don't gamble on the future, act now, without delay. – Simone de Beauvoir"
]; 