const QUOTES = [
  "Success is not final; failure is not fatal: It is the courage to continue that counts. – Winston Churchill",
  "The only way to do great work is to love what you do. – Steve Jobs",
  "Don’t let yesterday take up too much of today. – Will Rogers",
  "You miss 100% of the shots you don’t take. – Wayne Gretzky",
  "The best way to get started is to quit talking and begin doing. – Walt Disney",
  "Don’t watch the clock; do what it does. Keep going. – Sam Levenson",
  "The future depends on what you do today. – Mahatma Gandhi",
  "If you are working on something that you really care about, you don’t have to be pushed. The vision pulls you. – Steve Jobs",
  "The secret of getting ahead is getting started. – Mark Twain",
  "It always seems impossible until it’s done. – Nelson Mandela",
  "Don’t count the days, make the days count. – Muhammad Ali",
  "The only impossible journey is the one you never begin. – Tony Robbins",
  "The harder the battle, the sweeter the victory. – Les Brown",
  "Success is walking from failure to failure with no loss of enthusiasm. – Winston Churchill",
  "The only place where success comes before work is in the dictionary. – Vidal Sassoon",
  "Perseverance is not a long race; it is many short races one after the other. – Walter Elliot",
  "If you want it, work for it.",
  "Don’t quit. Suffer now and live the rest of your life as a champion. – Muhammad Ali",
  "Great things are done by a series of small things brought together. – Vincent Van Gogh",
  "The best revenge is massive success. – Frank Sinatra",
  "You’ve got to get up every morning with determination if you’re going to go to bed with satisfaction. – George Lorimer",
  "The difference between ordinary and extraordinary is that little extra. – Jimmy Johnson",
  "Do what you can, with what you have, where you are. – Theodore Roosevelt",
  "Don’t limit your challenges. Challenge your limits.",
  "Dream big and dare to fail. – Norman Vaughan",
  "The only person you are destined to become is the person you decide to be. – Ralph Waldo Emerson",
  "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart. – Roy T. Bennett",
  "Start where you are. Use what you have. Do what you can. – Arthur Ashe",
  "You are never too old to set another goal or to dream a new dream. – C.S. Lewis",
  "If you can dream it, you can do it. – Walt Disney",
  "Act as if what you do makes a difference. It does. – William James",
  "The journey of a thousand miles begins with one step. – Lao Tzu",
  "Don’t stop when you’re tired. Stop when you’re done.",
  "The best time to plant a tree was 20 years ago. The second best time is now. – Chinese Proverb",
  "You don’t have to be great to start, but you have to start to be great. – Zig Ziglar",
  "What you do today can improve all your tomorrows. – Ralph Marston",
  "Opportunities don’t happen, you create them. – Chris Grosser",
  "Everything you’ve ever wanted is on the other side of fear. – George Addair",
  "Don’t wait for opportunity. Create it.",
  "The sun himself is weak when he first rises, and gathers strength and courage as the day gets on. – Charles Dickens",
  "The only limit to our realization of tomorrow is our doubts of today. – Franklin D. Roosevelt",
  "Success is the sum of small efforts, repeated day in and day out. – Robert Collier",
  "If you’re going through hell, keep going. – Winston Churchill",
  "Failure is another stepping stone to greatness. – Oprah Winfrey",
  "I never dreamed about success, I worked for it. – Estée Lauder",
  "Don’t let someone else’s opinion of you become your reality. – Les Brown",
  "Keep your eyes on the stars and your feet on the ground. – Theodore Roosevelt",
  "Set your goals high, and don’t stop till you get there. – Bo Jackson",
  "Small progress is still progress.",
  "Hustle in silence and let your success make the noise.",
  "Motivation is what gets you started. Habit is what keeps you going. – Jim Rohn",
  "The difference between try and triumph is just a little umph! – Marvin Phillips",
  "Don’t settle for average. Bring your best to the moment. Then, whether it fails or succeeds, at least you know you gave all you had. – Angela Bassett",
  "You miss 100% of the shots you don’t take. – Wayne Gretzky",
  "Success usually comes to those who are too busy to be looking for it. – Henry David Thoreau",
  "The only way to achieve the impossible is to believe it is possible. – Charles Kingsleigh",
  "Don’t regret the past, just learn from it. – Ben Ipock",
  "The future belongs to those who believe in the beauty of their dreams. – Eleanor Roosevelt",
  "Believe in yourself and all that you are. – Christian D. Larson",
  "Energy and persistence conquer all things. – Benjamin Franklin",
  "Strive not to be a success, but rather to be of value. – Albert Einstein",
  "Do something today that your future self will thank you for.",
  "The secret of success is to do the common thing uncommonly well. – John D. Rockefeller Jr.",
  "Don’t look at your feet to see if you are doing it right. Just dance. – Anne Lamott",
  "The mind is everything. What you think you become. – Buddha",
  "Failure will never overtake me if my determination to succeed is strong enough. – Og Mandino",
  "Aim for the moon. If you miss, you may hit a star. – W. Clement Stone",
  "Don’t bunt. Aim out of the ballpark. Aim for the company of immortals. – David Ogilvy",
  "The greater the difficulty, the more the glory in surmounting it. – Epicurus",
  "The battles that count aren’t the ones for gold medals. The struggles within yourself—the invisible, inevitable battles inside all of us—that’s where it’s at. – Jesse Owens",
  "The most common way people give up their power is by thinking they don’t have any. – Alice Walker",
  "You can’t be that kid standing at the top of the waterslide, overthinking it. You have to go down the chute. – Tina Fey",
  "Don’t worry about failure; you only have to be right once. – Drew Houston",
  "The best way out is always through. – Robert Frost",
  "The only one who can tell you ‘you can’t win’ is you, and you don’t have to listen. – Jessica Ennis",
  "If you really want to do something, you’ll find a way. If you don’t, you’ll find an excuse. – Jim Rohn",
  "You’ve got to get up every morning with determination if you’re going to go to bed with satisfaction. – George Lorimer",
  "Don’t let the fear of losing be greater than the excitement of winning. – Robert Kiyosaki",
  "The man who moves a mountain begins by carrying away small stones. – Confucius",
  "The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty. – Winston Churchill",
  "The only difference between ordinary and extraordinary is that little extra.",
  "What you get by achieving your goals is not as important as what you become by achieving your goals. – Zig Ziglar",
  "You are capable of more than you know. – Benjamin Spock",
  "Don’t stop until you’re proud.",
  "Everything negative – pressure, challenges – is all an opportunity for me to rise. – Kobe Bryant",
  "Success is not about the destination, it’s about the journey. – Zig Ziglar",
  "The best way to predict the future is to create it. – Peter Drucker",
  "Believe you can and you’re halfway there. – Theodore Roosevelt",
  "Work hard in silence, let your success be the noise.",
  "Magic is believing in yourself. – Johann Wolfgang von Goethe",
  "Life is 10% what happens to us and 90% how we react to it. – Charles R. Swindoll",
  "Don’t wait for the perfect time and place to enter, for you are already onstage. – Unknown",
  "You don’t need to see the whole staircase, just take the first step. – Martin Luther King Jr.",
  "The road to success and the road to failure are almost exactly the same. – Colin R. Davis",
  "Success is getting what you want; happiness is wanting what you get. – W. P. Kinsella",
  "The standard you walk past is the standard you accept. – David Hurley",
  "Optimism is the faith that leads to achievement. Nothing can be done without hope and confidence. – Helen Keller",
  "Success is peace of mind, which is a direct result of self-satisfaction in knowing you made the effort to become the best of which you are capable. – John Wooden",
  "Success is stumbling from failure to failure with no loss of enthusiasm. – Winston Churchill",
  "Develop success from failures. Discouragement and failure are two of the surest stepping stones to success. – Dale Carnegie",
  "Nothing in the world can take the place of persistence. Talent will not; nothing is more common than unsuccessful men with talent. Genius will not; unrewarded genius is almost a proverb. Education will not; the world is full of educated derelicts. The slogan ’Press On’ has solved and always will solve the problems of the human race. – Calvin Coolidge"
]; 